# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.CharField(default='Unknown Job Title', max_length=64),
        ),
    ]
