# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20180207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skills',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
