# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20180207_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='date_entered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_sponsored',
            field=models.BooleanField(default=False, verbose_name='Sponsored'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
