# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20180207_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skills',
            field=models.CharField(help_text='Separate entries with a comma and no space.', max_length=500),
        ),
    ]
