# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20180208_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='skills',
            field=models.TextField(help_text='Separate entries with a comma and no space.', max_length=500),
        ),
    ]
