# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20180208_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobskill',
            name='category',
            field=models.CharField(choices=[('data_scientist', 'Data Scientist'), ('', '')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill'),
            preserve_default=False,
        ),
    ]
