# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20180208_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='category',
            field=models.CharField(choices=[('data_scientist', 'Data Scientist'), ('', '')], max_length=64),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.CharField(max_length=64),
        ),
    ]
