# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20180208_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, default='', to='Site.JobSkill'),
        ),
    ]
