# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_auto_20180208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('data_scientist', 'Data Scientist'), ('', '')], default='', max_length=64),
        ),
    ]
