# Generated by Django 2.0.1 on 2018-02-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_jobposting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
    ]
