# Generated by Django 2.0.1 on 2018-02-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20180209_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskillcount',
            name='test',
            field=models.CharField(default='', max_length=64),
        ),
    ]
