# Generated by Django 2.0.1 on 2018-02-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_jobskillcount_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobskillcount',
            name='job_skill',
        ),
        migrations.RemoveField(
            model_name='jobskillcount',
            name='test',
        ),
    ]
