# Generated by Django 2.0.1 on 2018-02-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20180209_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskillcount',
            name='job_skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill'),
        ),
        migrations.AddField(
            model_name='jobskillcount',
            name='posted_count',
            field=models.IntegerField(default=0),
        ),
    ]
