# Generated by Django 2.0.1 on 2018-02-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_auto_20180209_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_count', models.IntegerField(default=0)),
                ('job_skill', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill')),
            ],
        ),
    ]
