# Generated by Django 2.0.1 on 2018-02-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_jobskillcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassDoorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.CharField(max_length=64)),
                ('dimension_type', models.CharField(blank=True, default='', max_length=64)),
                ('month', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, default='', max_length=64)),
                ('measure', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('yoy', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State abbreviations only.', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='category',
            field=models.CharField(choices=[('data_scientist', 'Data Scientist'), ('test', 'Test')], max_length=64),
        ),
        migrations.AlterField(
            model_name='jobskillcount',
            name='job_skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.JobSkill'),
        ),
    ]
