# Generated by Django 2.0.1 on 2018-02-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_jobskillcount'),
        ('Site', '0012_auto_20180215_2026'),
    ]

    operations = [
    ]
