# Generated by Django 2.0.1 on 2018-03-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_geography_jobskillregiondatecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(default='', max_length=64)),
                ('CountryCode', models.IntegerField(default=-1)),
                ('Area', models.CharField(default='', max_length=64)),
                ('AreaCode', models.IntegerField(default=-1)),
                ('City', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('data_scientist', 'Data Scientist'), ('test', 'Test')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobskillregiondatecount',
            name='job_skill',
        ),
        migrations.AddField(
            model_name='jobskillregiondatecount',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.Jobs'),
        ),
        migrations.AddField(
            model_name='jobskillregiondatecount',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.Skills'),
        ),
    ]
